spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yml
    enabled: true
    drop-first: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

encryption:
  secret: ${ENCRYPTION_SECRET}

server:
  port: 8080